# -*- coding: utf-8 -*-
"""IDSC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xti08kCw-9M0-9ObAKvjOsG5ECaerHR5
"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/IDSC/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0.zip"

import zipfile

extract_path = "/content/hygd"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

os.listdir("/content/hygd")

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, roc_auc_score, roc_curve,
    confusion_matrix, ConfusionMatrixDisplay
)
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from torch.optim.lr_scheduler import CosineAnnealingLR
import warnings
warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────
# 0. CONFIG — GANTI SESUAI PATH KAMU
# ─────────────────────────────────────────────
DATA_ROOT    = "/content/hygd/hillel-yaffe-glaucoma-dataset-hygd-a-gold-standard-annotated-fundus-dataset-for-glaucoma-detection-1.0.0"          # folder berisi Images/ dan Labels.csv
IMAGES_DIR   = os.path.join(DATA_ROOT, "Images")
LABELS_CSV   = os.path.join(DATA_ROOT, "Labels.csv")
OUTPUT_DIR   = "./outputs"
SEED         = 42
IMG_SIZE     = 224
BATCH_SIZE   = 16
EPOCHS       = 30
LR           = 1e-4
MIN_QUALITY  = 3                 # filter gambar kualitas rendah (1-10)
DEVICE       = torch.device("cuda" if torch.cuda.is_available() else "cpu")

os.makedirs(OUTPUT_DIR, exist_ok=True)
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
print(f"Device: {DEVICE}")
print(f"PyTorch: {torch.__version__}")

image_files = os.listdir(IMAGES_DIR)
print("Jumlah file di folder Images:", len(image_files))

# lihat beberapa contoh nama file
print("Contoh file:", image_files[:5])

# ─────────────────────────────────────────────
# 1. LOAD & EXPLORATORY DATA ANALYSIS
# ─────────────────────────────────────────────
def load_and_eda(labels_csv, min_quality=3):
    df = pd.read_csv(labels_csv)
    print("\n━━━ RAW DATASET ━━━")
    print(df.head())
    print(f"\nTotal images : {len(df)}")
    print(f"GON+ (glaucoma) : {(df['Label'] == 'GON+').sum()}")
    print(f"GON- (normal)   : {(df['Label'] == 'GON-').sum()}")
    print(f"Quality Score stats:\n{df['Quality Score'].describe()}")

    # Filter berdasarkan quality score
    df_filtered = df[df["Quality Score"] >= min_quality].copy()
    print(f"\nSetelah filter quality >= {min_quality}: {len(df_filtered)} images")

    # Binary label
    df_filtered["label_int"] = (df_filtered["Label"] == "GON+").astype(int)

    # Plot distribusi
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    df_filtered["Label"].value_counts().plot(kind="bar", ax=axes[0], color=["#e63946", "#457b9d"])
    axes[0].set_title("Class Distribution (after quality filter)")
    axes[0].set_xlabel(""); axes[0].tick_params(rotation=0)

    df_filtered["Quality Score"].hist(ax=axes[1], bins=10, color="#2a9d8f", edgecolor="white")
    axes[1].set_title("Quality Score Distribution")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "eda_plots.png"), dpi=150)
    plt.close()
    print("EDA plot disimpan ke outputs/eda_plots.png")

    return df_filtered

# ─────────────────────────────────────────────
# 2. PATIENT-LEVEL SPLIT (anti data leakage!)
# ─────────────────────────────────────────────
def patient_level_split(df, test_size=0.15, val_size=0.15, seed=42):
    """
    Split berdasarkan Patient ID — BUKAN per gambar.
    Ini krusial karena 1 pasien bisa punya banyak gambar.
    Kalau split per gambar → data leakage → hasil ngeprank.
    """
    patients = df["Patient"].unique()

    # Stratified split berdasarkan majority label per patient
    patient_labels = df.groupby("Patient")["label_int"].agg(
        lambda x: int(x.mean() >= 0.5)
    ).reset_index()
    patient_labels.columns = ["Patient", "patient_label"]

    p_train_val, p_test = train_test_split(
        patient_labels["Patient"],
        test_size=test_size,
        stratify=patient_labels["patient_label"],
        random_state=seed
    )
    val_ratio = val_size / (1 - test_size)
    p_train, p_val = train_test_split(
        p_train_val,
        test_size=val_ratio,
        stratify=patient_labels[patient_labels["Patient"].isin(p_train_val)]["patient_label"],
        random_state=seed
    )

    train_df = df[df["Patient"].isin(p_train)].reset_index(drop=True)
    val_df   = df[df["Patient"].isin(p_val)].reset_index(drop=True)
    test_df  = df[df["Patient"].isin(p_test)].reset_index(drop=True)

    print(f"\n━━━ PATIENT-LEVEL SPLIT ━━━")
    print(f"Train: {len(train_df)} images ({train_df['Patient'].nunique()} patients)")
    print(f"Val  : {len(val_df)} images ({val_df['Patient'].nunique()} patients)")
    print(f"Test : {len(test_df)} images ({test_df['Patient'].nunique()} patients)")

    # Cek tidak ada overlap
    assert len(set(p_train) & set(p_val)) == 0, "OVERLAP TRAIN-VAL!"
    assert len(set(p_train) & set(p_test)) == 0, "OVERLAP TRAIN-TEST!"
    print("✓ Tidak ada patient overlap antar split")

    return train_df, val_df, test_df

# ─────────────────────────────────────────────
# 3. DATASET CLASS
# ─────────────────────────────────────────────
class HYGDDataset(Dataset):
    def __init__(self, df, images_dir, transform=None):
        self.df = df
        self.images_dir = images_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(self.images_dir, row["Image Name"])
        image = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        label = torch.tensor(row["label_int"], dtype=torch.long)
        return image, label


def get_transforms(img_size=224):
    """Augmentasi agresif untuk training, clean untuk val/test"""
    train_tf = transforms.Compose([
        transforms.Resize((img_size + 32, img_size + 32)),
        transforms.RandomCrop(img_size),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomVerticalFlip(p=0.3),
        transforms.RandomRotation(degrees=20),
        transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),
        transforms.RandomGrayscale(p=0.05),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    val_tf = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    return train_tf, val_tf

# ─────────────────────────────────────────────
# 4. MODEL — EfficientNet-B3 dengan Fine-tuning
# ─────────────────────────────────────────────
def build_model(num_classes=2, freeze_backbone=False):
    """
    EfficientNet-B3 pretrained ImageNet.
    Lebih ringan dari ResNet tapi akurasi lebih tinggi untuk medical imaging.
    """
    model = models.efficientnet_b3(weights=models.EfficientNet_B3_Weights.IMAGENET1K_V1)

    if freeze_backbone:
        for param in model.parameters():
            param.requires_grad = False

    # Ganti classifier head
    in_features = model.classifier[1].in_features
    model.classifier = nn.Sequential(
        nn.Dropout(p=0.4),
        nn.Linear(in_features, 256),
        nn.ReLU(),
        nn.Dropout(p=0.3),
        nn.Linear(256, num_classes)
    )
    return model

# ─────────────────────────────────────────────
# 5. TRAINING
# ─────────────────────────────────────────────
def compute_class_weights(train_df):
    """Handle class imbalance dengan class weights"""
    counts = train_df["label_int"].value_counts().sort_index()
    total = len(train_df)
    weights = torch.tensor(
        [total / (2 * counts[i]) for i in range(2)],
        dtype=torch.float
    ).to(DEVICE)
    print(f"\nClass weights: GON-={weights[0]:.3f}, GON+={weights[1]:.3f}")
    return weights


def train_one_epoch(model, loader, criterion, optimizer):
    model.train()
    total_loss, correct, total = 0, 0, 0
    for imgs, labels in loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += imgs.size(0)
    return total_loss / total, correct / total


@torch.no_grad()
def evaluate(model, loader, criterion):
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_probs, all_labels = [], []
    for imgs, labels in loader:
        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        total_loss += loss.item() * imgs.size(0)
        probs = torch.softmax(outputs, dim=1)[:, 1]
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += imgs.size(0)
        all_probs.extend(probs.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
    auc = roc_auc_score(all_labels, all_probs)
    return total_loss / total, correct / total, auc, all_probs, all_labels


def train_model(model, train_loader, val_loader, class_weights, epochs=30, lr=1e-4):
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)

    best_auc = 0
    best_model_path = os.path.join(OUTPUT_DIR, "best_model.pth")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": [], "val_auc": []}

    print("\n━━━ TRAINING ━━━")
    for epoch in range(1, epochs + 1):
        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer)
        vl_loss, vl_acc, vl_auc, _, _ = evaluate(model, val_loader, criterion)
        scheduler.step()

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(vl_loss)
        history["train_acc"].append(tr_acc)
        history["val_acc"].append(vl_acc)
        history["val_auc"].append(vl_auc)

        if vl_auc > best_auc:
            best_auc = vl_auc
            torch.save(model.state_dict(), best_model_path)
            flag = " ← BEST"
        else:
            flag = ""

        print(f"Epoch {epoch:02d}/{epochs} | "
              f"Loss: {tr_loss:.4f}/{vl_loss:.4f} | "
              f"Acc: {tr_acc:.3f}/{vl_acc:.3f} | "
              f"Val AUC: {vl_auc:.4f}{flag}")

    print(f"\n✓ Best Val AUC: {best_auc:.4f} → disimpan ke {best_model_path}")
    return history, best_model_path


def plot_training_history(history):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    axes[0].plot(history["train_loss"], label="Train")
    axes[0].plot(history["val_loss"], label="Val")
    axes[0].set_title("Loss"); axes[0].legend()

    axes[1].plot(history["train_acc"], label="Train")
    axes[1].plot(history["val_acc"], label="Val")
    axes[1].set_title("Accuracy"); axes[1].legend()

    axes[2].plot(history["val_auc"], color="purple")
    axes[2].set_title("Val AUC-ROC")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "training_history.png"), dpi=150)
    plt.close()
    print("Training history plot disimpan ke outputs/training_history.png")

# ─────────────────────────────────────────────
# 6. EVALUASI FINAL DI TEST SET
# ─────────────────────────────────────────────
def final_evaluation(model, test_loader, class_weights):
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    _, acc, auc, all_probs, all_labels = evaluate(model, test_loader, criterion)
    preds = [1 if p >= 0.5 else 0 for p in all_probs]

    print("\n━━━ FINAL TEST RESULTS ━━━")
    print(f"Accuracy : {acc:.4f}")
    print(f"AUC-ROC  : {auc:.4f}")
    print("\nClassification Report:")
    print(classification_report(all_labels, preds, target_names=["GON-", "GON+"]))

    # Confusion Matrix
    cm = confusion_matrix(all_labels, preds)
    disp = ConfusionMatrixDisplay(cm, display_labels=["GON-", "GON+"])
    fig, ax = plt.subplots(figsize=(6, 5))
    disp.plot(ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(f"Confusion Matrix (Test AUC={auc:.4f})")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrix.png"), dpi=150)
    plt.close()

    # ROC Curve
    fpr, tpr, _ = roc_curve(all_labels, all_probs)
    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, color="#e63946", lw=2, label=f"AUC = {auc:.4f}")
    plt.plot([0, 1], [0, 1], "k--", lw=1)
    plt.xlabel("FPR"); plt.ylabel("TPR")
    plt.title("ROC Curve — Test Set")
    plt.legend(); plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "roc_curve.png"), dpi=150)
    plt.close()
    print("Plots disimpan ke outputs/")

    return auc

# ─────────────────────────────────────────────
# 7. GRADCAM — Interpretability (WAJIB untuk kompetisi!)
# ─────────────────────────────────────────────
class GradCAM:
    """
    Grad-CAM untuk EfficientNet.
    Menghasilkan heatmap yang menunjukkan AREA MANA yang dipakai model
    untuk memutuskan glaukoma — ini yang bikin juri terkesan.
    """
    def __init__(self, model, target_layer):
        self.model = model
        self.gradients = None
        self.activations = None
        target_layer.register_forward_hook(self._save_activation)
        target_layer.register_backward_hook(self._save_gradient)

    def _save_activation(self, module, input, output):
        self.activations = output.detach()

    def _save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()

    def generate(self, img_tensor, class_idx=None):
        self.model.eval()
        img_tensor = img_tensor.unsqueeze(0).to(DEVICE)
        output = self.model(img_tensor)

        if class_idx is None:
            class_idx = output.argmax(dim=1).item()

        self.model.zero_grad()
        output[0, class_idx].backward()

        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        cam = (weights * self.activations).sum(dim=1, keepdim=True)
        cam = torch.relu(cam).squeeze().cpu().numpy()
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)
        return cam, class_idx


def visualize_gradcam(model, dataset, n_samples=6):
    """Simpan GradCAM untuk n sampel dari test set"""
    # Target layer terakhir EfficientNet features
    target_layer = model.features[-1]
    gradcam = GradCAM(model, target_layer)

    val_tf = get_transforms(IMG_SIZE)[1]
    indices = random.sample(range(len(dataset)), min(n_samples, len(dataset)))

    fig, axes = plt.subplots(n_samples, 3, figsize=(12, 4 * n_samples))
    if n_samples == 1:
        axes = [axes]

    label_names = {0: "GON- (Normal)", 1: "GON+ (Glaucoma)"}

    for i, idx in enumerate(indices):
        img_tensor, true_label = dataset[idx]

        # Original image (denormalize)
        mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
        std  = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
        img_denorm = (img_tensor * std + mean).clamp(0, 1).permute(1, 2, 0).numpy()

        # GradCAM
        cam, pred_idx = gradcam.generate(img_tensor)
        cam_resized = np.array(Image.fromarray(
            (cam * 255).astype(np.uint8)
        ).resize((IMG_SIZE, IMG_SIZE))) / 255.0

        # Overlay
        heatmap = cm.jet(cam_resized)[..., :3]
        overlay = (0.5 * img_denorm + 0.5 * heatmap).clip(0, 1)

        axes[i][0].imshow(img_denorm); axes[i][0].set_title(f"Original\nTrue: {label_names[true_label.item()]}")
        axes[i][1].imshow(cam_resized, cmap="jet"); axes[i][1].set_title("GradCAM Heatmap")
        axes[i][2].imshow(overlay); axes[i][2].set_title(f"Overlay\nPred: {label_names[pred_idx]}")
        for ax in axes[i]: ax.axis("off")

    plt.suptitle("GradCAM — Model Interpretability", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "gradcam_results.png"), dpi=150)
    plt.close()
    print("GradCAM disimpan ke outputs/gradcam_results.png")

# ─────────────────────────────────────────────
# 8. MAIN PIPELINE
# ─────────────────────────────────────────────
def main():
    print("=" * 60)
    print("  HYGD Glaucoma Pipeline — IDSC 2026")
    print("=" * 60)

    # Step 1: Load & EDA
    df = load_and_eda(LABELS_CSV, min_quality=MIN_QUALITY)

    # Step 2: Patient-level split
    train_df, val_df, test_df = patient_level_split(df, seed=SEED)

    # Step 3: Transforms & Datasets
    train_tf, val_tf = get_transforms(IMG_SIZE)
    train_ds = HYGDDataset(train_df, IMAGES_DIR, train_tf)
    val_ds   = HYGDDataset(val_df, IMAGES_DIR, val_tf)
    test_ds  = HYGDDataset(test_df, IMAGES_DIR, val_tf)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

    # Step 4: Model
    model = build_model(num_classes=2).to(DEVICE)
    print(f"\nModel: EfficientNet-B3")
    total_params = sum(p.numel() for p in model.parameters())
    trainable   = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Total params: {total_params:,} | Trainable: {trainable:,}")

    # Step 5: Class weights
    class_weights = compute_class_weights(train_df)

    # Step 6: Training (Phase 1 — full fine-tune)
    history, best_path = train_model(model, train_loader, val_loader, class_weights, EPOCHS, LR)
    plot_training_history(history)

    # Step 7: Load best model & evaluate
    model.load_state_dict(torch.load(best_path, map_location=DEVICE))
    final_auc = final_evaluation(model, test_loader, class_weights)

    # Step 8: GradCAM
    print("\n━━━ GENERATING GRADCAM ━━━")
    visualize_gradcam(model, test_ds, n_samples=6)

    print("\n" + "=" * 60)
    print(f"  PIPELINE SELESAI! Final Test AUC: {final_auc:.4f}")
    print(f"  Semua output tersimpan di folder: {OUTPUT_DIR}/")
    print("=" * 60)
    print("\nFile outputs:")
    print("  ├── best_model.pth        → model terbaik")
    print("  ├── eda_plots.png         → eksplorasi data")
    print("  ├── training_history.png  → kurva training")
    print("  ├── confusion_matrix.png  → evaluasi test")
    print("  ├── roc_curve.png         → ROC & AUC")
    print("  └── gradcam_results.png   → interpretability")


if __name__ == "__main__":
    main()

import shutil
from google.colab import files

shutil.make_archive('hygd_outputs', 'zip', './outputs')
files.download('hygd_outputs.zip')

